version: '3.8'

services:
  network-monitor:
    build: .
    container_name: network-monitor
    # We expose the port so Prometheus can access it, but it's not strictly necessary for the host
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    command: ["python", "./network_monitor.py", "--log-file", "logs/connection_log.txt"]
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - network-monitor
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      # Provisioning directories to automatically add data sources and dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    restart: unless-stopped

# Define volumes for persistent data storage
volumes:
  prometheus_data:
  grafana_data:
